use crate::extractor::BlueprintPoint;
use anyhow::{Context, Result};
use chrono::Local;
use std::path::{Path, PathBuf};

/// Write a markdown file with the blueprint points (and optionally the transcript).
/// Returns the path to the written file.
pub fn save_markdown(
    audio_path: &Path,
    transcript: &str,
    points: &[BlueprintPoint],
    out_dir: &Path,
    include_transcript: bool,
) -> Result<PathBuf> {
    let now = Local::now();
    let timestamp = now.format("%Y-%m-%d_%H%M");

    let stem = audio_path
        .file_stem()
        .unwrap_or_default()
        .to_string_lossy()
        .to_string();

    // Sanitize stem for filename use
    let safe_stem: String = stem
        .chars()
        .map(|c| if c.is_alphanumeric() || c == '-' || c == '_' { c } else { '_' })
        .collect();

    let filename = format!("{timestamp}_{safe_stem}_blueprint.md");

    std::fs::create_dir_all(out_dir)
        .with_context(|| format!("Could not create output directory: {}", out_dir.display()))?;

    let out_path = out_dir.join(&filename);

    let mut md = String::new();

    // ── Header ───────────────────────────────────────────────────────────────
    md.push_str(&format!(
        "# Blueprint: {}\n\n",
        stem.replace('_', " ").replace('-', " ")
    ));
    md.push_str(&format!(
        "> Generated on **{}**  \n",
        now.format("%B %d, %Y at %H:%M")
    ));
    md.push_str(&format!(
        "> Source: `{}`  \n",
        audio_path.file_name().unwrap().to_string_lossy()
    ));
    md.push_str(&format!(
        "> Word count: {} words\n\n",
        transcript.split_whitespace().count()
    ));

    md.push_str("---\n\n");

    // ── Blueprint Points ─────────────────────────────────────────────────────
    md.push_str("## 🗺 Blueprint Points\n\n");

    for (i, point) in points.iter().enumerate() {
        md.push_str(&format!("### {}. {}\n\n", i + 1, point.title));
        md.push_str(&format!("{}\n\n", point.insight));
        md.push_str(&format!("**Implication →** {}\n\n", point.implication));
    }

    md.push_str("---\n\n");

    // ── Transcript (optional) ────────────────────────────────────────────────
    if include_transcript {
        md.push_str("## 📝 Full Transcript\n\n");
        md.push_str(transcript);
        md.push_str("\n\n---\n\n");
    }

    md.push_str("*Generated by [Blueprint CLI](https://github.com/you/blueprint)*\n");

    std::fs::write(&out_path, md)
        .with_context(|| format!("Could not write markdown to: {}", out_path.display()))?;

    Ok(out_path)
}
